apiVersion: v1
kind: Service
metadata:
  name: kafka-ui
  namespace: helpdesk
spec:
  type: NodePort
  selector:
    app: kafka-ui
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30081
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-ui
  namespace: helpdesk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-ui
  template:
    metadata:
      labels:
        app: kafka-ui
        app.kubernetes.io/part-of: helpdesk
    spec:
      containers:
        - name: kafka-ui
          image: provectuslabs/kafka-ui:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: KAFKA_CLUSTERS_0_NAME
              value: helpdesk-kubernetes
            - name: KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS
              value: kafka:9092
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 768Mi
---
apiVersion: v1
kind: Service
metadata:
  name: redis-insight
  namespace: helpdesk
spec:
  type: NodePort
  selector:
    app: redis-insight
  ports:
    - name: http
      port: 5540
      targetPort: 5540
      nodePort: 30540
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-insight
  namespace: helpdesk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-insight
  template:
    metadata:
      labels:
        app: redis-insight
        app.kubernetes.io/part-of: helpdesk
    spec:
      containers:
        - name: redis-insight
          image: redis/redisinsight:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 5540
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 768Mi
